# Generated by Django 4.2.6 on 2023-10-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_formset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlemodel',
            table='articleModel',
        ),
    ]
